### ISSUE TITLE
Add unique class for social links item

### ISSUE THREAD

**Issue by samikeijonen** [ZeelandFamily/zf-social-share#6]
In social links item `<li class="social-links__item">` there would be nice that have unique class just in case for different styling. 

Example: `<li class="social-links__item social-links__item-facebook">`

**Comment by danielck** [comment]
Good idea. For the classname I suggest following our usual way of BEM-style notation with two hyphens, like so: `social-links__item--facebook`.

**Comment by samikeijonen** [comment]
I personally only use `social-links-item-facebook` but I don't know if that's coming from any standards.

**Comment by danielck** [comment]
@samikeijonen nothing wrong with that at all, but the rest of the plugin already uses the `parent__subelement--mod` pattern, which we (mostly) use in theme development too.

**Comment by Ahmis** [comment]
Done!
